### ISSUE TITLE
Locate and expedite W8LS16909

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/archive-issues#1]
W8LS16909 -     rdzogs pa chen po dbyings rig mdzod kyi mchan 'grel/ was cataloged as part of DPL-480 on 2 Dec 2015 and there are several users (kurt.keutzer@gmail.com and jeanluc.achard@sfr.fr) who have requested this work be made available as soon as possible back in December.

Please locate the work and report status and estimated time to deposit in the archive.

**Comment by xristy** [comment]
When the images for W8LS16909 are received from the field please update this issue with the status so that the interested users can be apprised that there is some progress

**Comment by Klhamo** [comment]
Not the only W8LS16909  case, we have  so many of them in on hold DPL-480-2015-ON-HOLD.

**Comment by TBRC-Travis** [comment]
Images have been synced to the website.
