### ISSUE TITLE
Updated images on S3 not reflected in pechaviewer

### ISSUE THREAD

**Issue by TBRC-Travis** [BuddhistDigitalResourceCenter/archive-issues#13]
I updated s3://archive.tbrc.org/Works/48/W1KG22562/images with new images but the pechaviewer is still displaying the old images - https://www.tbrc.org/#library_work_ViewInWIndow-W1KG22562%7CI1KG22632%7C1%7C1%7C1%7C214

**Comment by xristy** [comment]
You'll have to manually delete the images from the 

    /home/ec2-user/image-cache 

and then from your machine do a:

    curl https://www.tbrc.org/browser/ImageService?refresh=yes

or from the ec2 instance do:

    curl http://localhost:15173/browser/ImageService?refresh=yes
