### ISSUE TITLE
W2PD17382 missing images in S3 archive

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/archive-issues#16]
volume 5 (I3PD1226). The image list shows images from 1 - 982 but only images 1 - 784 are in the s3 archive

volume 6 (I3PD1227) there are supposedly pp 1 - 430 but all that appears in s3 are 1 - 418

vol 7 (I3PD1228) should be 1 - 750; actual 1 - 714

Please check remaining volumes 8 - 39 and either upload missing images or correct the image lists in the corresponding imagegroups

**Comment by TBRC-Travis** [comment]
The image files in S3 matches what is present in the archive.  It appears the image lists are wrong.

**Comment by TBRC-Travis** [comment]
Updated page listings for all volumes.  This should be fixed now.
