### ISSUE TITLE
move DPL-480-2015-ON-HOLD to /Incoming

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/archive-issues#2]
Please move the DPL-480-2015-ON-HOLD folder to /Incoming since it does not contain the images necessary for /Processing.

**Comment by TBRC-Travis** [comment]
We talked about moving the ON-HOLD folder to Incoming about 6 months ago but then decided to leave it in Processing to ease transfer of files to the DPL-480-2015-TO-PROCESS folder for the Librarians, so I'm not exactly sure we want to take action on this issue.  

Once a particular work in the ON-HOLD folder is ready for Processing a simple drag and drop from a single window will move the files to the TO-PROCESS folder and that's all that needs to be done.  But if we move ON-HOLD to Incoming then the Librarians will need to open two Finder windows and then drag and drop to _copy_ the folder over to TO-PROCESS and then they will also need to remember to delete it from Incoming once the copy has finished.

**Comment by xristy** [comment]
I fail to see why dragging an item from /Incoming/DPL-480-2015-ON-HOLD to /Processing/TO-PROCESS and then deleting the items from /Incoming is 1) so onerous as to warrant creating a confused organization of content; and 2) remarkably different in any useful way from what is supposed to be going on with other non-DPL-480 items that are first deposited in /Incoming somewheres and examined by Karma to ensure goodness and then dragged-dropped-and-deleted from /Incoming to Processing.

The purpose of /Incoming and /Processing is to provide some organization to the workflow and the status of material in /Processing and /Incoming should match the common meaning of the names of the two chunks of content.

By not following a discipline of using the two chunks we make it more difficult for casual users who may peruse /Incoming and /Processing to readily understand what is going on in those two chunks. This has once again become an issue owing to W8LS16909 which Kurt Keutzer has an interest in. He went wandering about in /Incoming and /Processing trying to figure out what the status of W8LS16909 was and was confused. I also was confused since the content was not organized according to logical principles. 

If everyone wants to do drag-and-drop in a single window then we could create a single shared folder, /InProgress with subfolders /InProgress/Incoming and /InProgress/Processing.

Enshrining an exception for one particular case doesn't seem prudent unless a clear rationale is provided.

**Comment by TBRC-Travis** [comment]
DPL-480-2015-ON-HOLD has been moved from /Processing to /Incoming/scans

**Comment by xristy** [comment]
Thanks!
