### ISSUE TITLE
Delete & redo W3MS999 images

### ISSUE THREAD

**Issue by TBRC-Travis** [BuddhistDigitalResourceCenter/archive-issues#3]
From @Klhamo -

"Please delete,  W3MS499 images, I am looking for correct images,  it may take sometime."

**Comment by TBRC-Travis** [comment]
Image files for W3MS499 have been deleted from Archive, WebArchive, and S3/Works

**Comment by Klhamo** [comment]
Thank you!

**Comment by xristy** [comment]
If this issue is finished then it should be closed

**Comment by TBRC-Travis** [comment]
It's not finalized.  We're waiting for Kelsang to find correct images.

**Comment by xristy** [comment]
Ok

**Comment by TBRC-Travis** [comment]
This has been resolved.  Images have been re-synced.
