### ISSUE TITLE
W00KG01654 images versus W00KG01655 images???

### ISSUE THREAD

**Issue by TBRC-Travis** [BuddhistDigitalResourceCenter/archive-issues#4]
I was looked at the images for W00KG01654 and the archive directory name indicated that the images can be removed in favor of W00KG01655.  Can we go ahead and delete the images for W00KG01654?

**Comment by TBRC-Travis** [comment]
Now I'm confused, because when I look at W00KG01655 there is a directory called "removed in favor of W00KG01654".  So I'm not sure which work has the definitive set of images.

**Comment by xristy** [comment]
That certainly is confusing!! I hope Karma will be able to clear up the situation.

**Comment by karmagongde** [comment]
Hi Travis, I looked at images of W00KG01654 and W00KG01655. The pagination
of the text is continuing. Therefore, please use W00KG01654 and combine the
images. I will change the catalogue title and necessary informations in
W00KG01654 and withdraw W00KG01655. Thank you.

**Comment by karmagongde** [comment]
I have consolidated the two works. I also renamed the images and uploaded
on Processing/Existing/Whole/W00KG01654. Please sync this and deleted
W00KG01655 from archive. Thank you.

**Comment by TBRC-Travis** [comment]
Thanks Karma!  I synced the revised W00KG01654 content and removed W00KG01655.
