### ISSUE TITLE
Organize 2015 US AID works by Tsering Samdrup

### ISSUE THREAD

**Issue by TBRC-Travis** [BuddhistDigitalResourceCenter/archive-issues#6]
There are a number of 2015 US AID works done by Tsering Samdrup that indicate we have received the images for but the files are not in Processing (see list below excerpted from RFP Master spreadsheet).  

It does look like many of these  works are available in /homes/FR-Samdup (for example I see W3MS115 is in /homes/FR- Samdup/DPE-DudulDorje/2015- Approved and paid/W3MS115-རེབ་གོང་ས་དཀྱིལ་དུ་བཞུགས་པའི་བྲིས་མ་སྐོར་ཞིག) but they are very disorganized.

Can we please organize the files & folders for these works and move all of them from "homes" to Processing?  Thank you!

W3MS33 
W3MS15
W3MS42
W3MS97
W3MS104
W3MS109
W3MS112
W3MS115
W3MS261
W3MS878
W3MS1149
W3MS543
W3MS552
W3MS652
W3MS565
W3MS684
W3MS643
W3MS677
W3MS701
W3MS1262

**Comment by Klhamo** [comment]
Good morning!

Yes, I received.


Wishing you every success and happiness!
             
                 ཏཱཾ྄ཿ
Kelsang Lhamo (བསྐལ་བཟང་ལྷ་མོའམ་ཆོས་འཛིན།)
Senior Research Associate 
བོད་ཀྱི་ནང་བསྟན་དཔེ་ཚོགས་ལྟེ་གནས། Tibetan Buddhist Resource Center 藏传佛教资源中心 
1430 Massachusetts Ave 5th Floor Cambridge, MA 02138 
ཁ་པར་. 617-354-7900 | skype. kelsanglhamo | tbrc.org <http://tbrc.org/>
Contributions to our ongoing work at TBRC are greatly appreciated.

**Comment by TBRC-Travis** [comment]
This has been resolved.
