### ISSUE TITLE
Need to organized W19884/archive

### ISSUE THREAD

**Issue by TBRC-Travis** [BuddhistDigitalResourceCenter/archive-issues#9]
W19884/archive contains the following folders:

W19884-ca-a
W19884-ca-b
W19884-ga-a
W19884-ga-b
W19884-ka-a
W19884-ka-b
W19884-kha-a
W19884-kha-b
W19884-nga-a
W19884-nga-b

I need help organizing these into the appropriate image group folders.

**Comment by karmagongde** [comment]
I arranged them, please check. and let me know.

**Comment by TBRC-Travis** [comment]
Looks good!  Thank you.
